#
# SSW CI
#
name: Java CI with Gradle

on: [push, pull_request]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    #
    # Perform a Release Build
    #
    - name: Build with Gradle
      run: ./gradlew zipRelease

    #
    # Upload release distribution zipfile
    #
    - name: Upload Releases
      uses: kittaakos/upload-artifact-as-is@v0

      with:
        path: ./build/distributions/
